apiVersion: v1
kind: ConfigMap
metadata:
  name: book-config
  namespace: book-demo
data:
  application.yml: |
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 30s